"""empty message

Revision ID: 54ca59c79708
Revises: 
Create Date: 2020-08-30 17:14:02.157980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54ca59c79708'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_transaction',
    sa.Column('created_at_utc', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('base_currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('transaction_currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('final_amount', sa.DECIMAL(precision=28, scale=8), nullable=False),
    sa.Column('transaction_amount', sa.DECIMAL(precision=28, scale=12), nullable=False),
    sa.Column('currency_rate', sa.DECIMAL(precision=28, scale=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currency_transaction_created_at_utc'), 'currency_transaction', ['created_at_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currency_transaction_created_at_utc'), table_name='currency_transaction')
    op.drop_table('currency_transaction')
    # ### end Alembic commands ###
